version: '3'
services:
  app:
    container_name: test-1
    restart: always
    build: .
    ports:
    - '8081:3000'
    depends_on:
      - mongo
    networks:
      - test-network
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - 'test-network'
networks:
  test-network:
    driver: bridge